### PR TITLE
proposed solution for issue #4

### PR DESCRIPTION
**Pull request by jsoeterbroek**
Proposed solution for issue #4, implementation of multiple languages in a simple way.

### CODE REVIEW

**Comment by bwbroersma** [comment]
Great! Didn't tried it yet, but maybe we shouldn't have a status field in the translation of a feature? Otherwise we might have different :vertical_traffic_light: states stored for the same feature.

**Comment by jsoeterbroek** [comment]
> This fixes it for the dutch site. Is it possible to also make it work for the english site?

This last change also fixes it for english site (or any other lang other than nl).

**Comment by PaulWagener** [comment]
I can't merge these changes because of the commit signing rule. The very first commit in this PR (https://github.com/minvws/nl-covid19-notification-app-dashboard/pull/9/commits/5aa7b320e31df8c1eb355baeecf9ac30e02cfa40) isn't signed. You'll have to open a new PR or do a force-push with all commits signed.

**Comment by jsoeterbroek** [comment]
Closed, new pull request

**Pull request closed without merging**
